import "./style.css";
import "./script/gallerySlider";
import "./script/phoneMask";
import "./script/reviewSlider";
import "./script/checked";
import "./script/selectMap";
import "./script/aboutModal";
import "./script/formAndResponseModal";
import "./script/checkErrorForm.ts";
